package com.forensic.bpa.export;

import com.forensic.bpa.spatial.Point3D;
import com.forensic.bpa.spatial.Ray3D;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

public class Scene3DObjExporter {

    public static void exportSceneToObj(
            String filepath,
            List<Ray3D> spatterRays,
            Point3D areaOfOrigin,
            Ray3D shooterVector,
            double maxShooterDistanceMeters
    ) throws IOException {
        if (filepath == null || filepath.isBlank()) {
            throw new IllegalArgumentException("A non-empty OBJ filepath is required.");
        }
        if (!isFinite(areaOfOrigin)) {
            areaOfOrigin = new Point3D(0, 0, 0);
        }
        if (shooterVector == null || shooterVector.direction() == null) {
            shooterVector = new Ray3D(areaOfOrigin, new Point3D(0, 0, -1));
        }
        if (!Double.isFinite(maxShooterDistanceMeters) || maxShooterDistanceMeters < 0) {
            maxShooterDistanceMeters = 0;
        }

        try (PrintWriter writer = new PrintWriter(new FileWriter(filepath))) {
            writer.println("# Forensic 3D Scene Trajectory Map");
            writer.println("# Generated by Computational BPA Pipeline\n");

            int vertexIndex = 1;

            // 1. Export Spatter Anchor Points and Trajectory Lines
            writer.println("o Spatter_Rays");
            for (Ray3D ray : spatterRays == null ? List.<Ray3D>of() : spatterRays) {
                if (ray == null || !isFinite(ray.anchor()) || !isFinite(ray.direction())) {
                    continue;
                }
                Point3D p1 = ray.anchor();
                Point3D p2 = p1.add(ray.direction().multiply(1.5)); // 1.5m ray representation

                writer.printf("v %.4f %.4f %.4f%n", p1.x(), p1.y(), p1.z());
                writer.printf("v %.4f %.4f %.4f%n", p2.x(), p2.y(), p2.z());

                writer.printf("l %d %d%n", vertexIndex, vertexIndex + 1);
                vertexIndex += 2;
            }

            // 2. Export Estimated Area of Origin Point
            writer.println("\no Area_Of_Origin");
            writer.printf("v %.4f %.4f %.4f%n", areaOfOrigin.x(), areaOfOrigin.y(), areaOfOrigin.z());
            writer.printf("p %d%n", vertexIndex);
            int originIndex = vertexIndex;
            vertexIndex++;

            // 3. Export Line of Fire (Extrapolated Shooter Ray)
            writer.println("\no Shooter_Line_Of_Fire");
            Point3D shooterTargetPos = areaOfOrigin.add(shooterVector.direction().multiply(maxShooterDistanceMeters));
            if (!isFinite(shooterTargetPos)) {
                shooterTargetPos = areaOfOrigin;
            }
            
            writer.printf("v %.4f %.4f %.4f%n", shooterTargetPos.x(), shooterTargetPos.y(), shooterTargetPos.z());
            writer.printf("l %d %d%n", originIndex, vertexIndex);
            if (writer.checkError()) {
                throw new IOException("Failed to write OBJ scene.");
            }
        }
    }

    private static boolean isFinite(Point3D point) {
        return point != null && Double.isFinite(point.x())
                && Double.isFinite(point.y()) && Double.isFinite(point.z());
    }
}
