// lib/TrustOfflineBuffer.js
const Database = require('better-sqlite3');
const crypto = require('crypto');

class TrustOfflineBuffer {
    /**
     * @param {string} dbPath - Path to local SQLite file (e.g., './data/trust_shell_queue.db')
     * @param {string} trustMainEndpoint - Target API URL (e.g., 'https://trust-main.internal/api/v1/telemetry/ingest')
     */
    constructor(dbPath = './trust_shell_queue.db', trustMainEndpoint) {
        this.dbPath = dbPath;
        this.trustMainEndpoint = trustMainEndpoint;
        this.db = new Database(this.dbPath);
        this.syncInterval = null;
        this.isSyncing = false;

        this._initDatabase();
    }

    /**
     * Initialize the local buffer table and index
     */
    _initDatabase() {
        this.db.pragma('journal_mode = WAL'); // High performance local write speed
        
        this.db.prepare(`
            CREATE TABLE IF NOT EXISTS payload_queue (
                queue_id TEXT PRIMARY KEY,
                master_shift_hash TEXT UNIQUE NOT NULL,
                module_type TEXT NOT NULL,
                badge_id TEXT NOT NULL,
                payload_json TEXT NOT NULL,
                status TEXT CHECK(status IN ('PENDING', 'SYNCING', 'SYNCED', 'FAILED')) DEFAULT 'PENDING',
                retry_count INTEGER DEFAULT 0,
                created_at TEXT NOT NULL,
                last_attempt_at TEXT,
                error_log TEXT
            )
        `).run();

        this.db.prepare(`
            CREATE INDEX IF NOT EXISTS idx_payload_status ON payload_queue(status, created_at);
        `).run();
    }

    /**
     * Enqueue a clockOut() payload generated by BaseFirstResponderModule
     * @param {Object} payload - Full payload object from clockOut()
     */
    enqueue(payload) {
        if (!payload || !payload.master_shift_hash) {
            throw new Error("Invalid payload: missing master_shift_hash.");
        }

        const queueId = `BUF_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`;
        const createdAt = new Date().toISOString();

        const stmt = this.db.prepare(`
            INSERT INTO payload_queue (
                queue_id, master_shift_hash, module_type, badge_id, payload_json, status, created_at
            ) VALUES (?, ?, ?, ?, ?, 'PENDING', ?)
        `);

        stmt.run(
            queueId,
            payload.master_shift_hash,
            payload.module || 'BASE_FIRST_RESPONDER',
            payload.badge_id || 'UNKNOWN',
            JSON.stringify(payload),
            createdAt
        );

        return { queueId, masterShiftHash: payload.master_shift_hash };
    }

    /**
     * Ping Trust-Main endpoint to check connection availability
     */
    async isOnline() {
        try {
            const controller = new AbortController();
            const timeoutId = setTimeout(() => controller.abort(), 3000); // 3s timeout

            const healthUrl = new URL('/api/v1/health', this.trustMainEndpoint).toString();
            const res = await fetch(healthUrl, { method: 'HEAD', signal: controller.signal });
            clearTimeout(timeoutId);

            return res.ok;
        } catch {
            return false;
        }
    }

    /**
     * Process all PENDING and FAILED (retry_count < maxRetries) payloads
     */
    async processQueue(maxRetries = 5) {
        if (this.isSyncing) return { processed: 0, status: 'ALREADY_RUNNING' };

        const online = await this.isOnline();
        if (!online) {
            return { processed: 0, status: 'OFFLINE' };
        }

        this.isSyncing = true;
        let syncedCount = 0;
        let failedCount = 0;

        // Fetch eligible records FIFO
        const selectStmt = this.db.prepare(`
            SELECT queue_id, master_shift_hash, payload_json, retry_count 
            FROM payload_queue 
            WHERE status IN ('PENDING', 'FAILED') AND retry_count < ?
            ORDER BY created_at ASC
            LIMIT 50
        `);

        const records = selectStmt.all(maxRetries);

        for (const record of records) {
            // Lock record status to SYNCING
            this.db.prepare(`UPDATE payload_queue SET status = 'SYNCING', last_attempt_at = ? WHERE queue_id = ?`)
                .run(new Date().toISOString(), record.queue_id);

            try {
                const response = await fetch(this.trustMainEndpoint, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-Trust-Shell-Signature': this._signPayload(record.payload_json)
                    },
                    body: record.payload_json
                });

                if (response.ok) {
                    // Mark SYNCED
                    this.db.prepare(`UPDATE payload_queue SET status = 'SYNCED', error_log = NULL WHERE queue_id = ?`)
                        .run(record.queue_id);
                    syncedCount++;
                } else {
                    const errText = `HTTP ${response.status}: ${await response.text()}`;
                    this._markFailed(record.queue_id, record.retry_count, errText);
                    failedCount++;
                }
            } catch (err) {
                this._markFailed(record.queue_id, record.retry_count, err.message);
                failedCount++;
            }
        }

        this.isSyncing = false;
        return { total: records.length, synced: syncedCount, failed: failedCount, status: 'COMPLETE' };
    }

    /**
     * Helper to mark a sync failure and update retry counters
     */
    _markFailed(queueId, currentRetryCount, errorMessage) {
        const stmt = this.db.prepare(`
            UPDATE payload_queue 
            SET status = 'FAILED', retry_count = ?, error_log = ?, last_attempt_at = ? 
            WHERE queue_id = ?
        `);
        stmt.run(currentRetryCount + 1, errorMessage, new Date().toISOString(), queueId);
    }

    /**
     * Cryptographic verification signature attached to outgoing sync requests
     */
    _signPayload(jsonString) {
        const secret = process.env.TRUST_SHELL_SECRET || 'TRUST_SHELL_LOCAL_KEY';
        return crypto.createHmac('sha256', secret).update(jsonString).digest('hex');
    }

    /**
     * Start background daemon loop to monitor connectivity and flush queue automatically
     */
    startAutoSync(intervalMs = 15000) {
        if (this.syncInterval) return;
        
        this.syncInterval = setInterval(async () => {
            await this.processQueue();
        }, intervalMs);
    }

    /**
     * Stop the auto-sync daemon loop
     */
    stopAutoSync() {
        if (this.syncInterval) {
            clearInterval(this.syncInterval);
            this.syncInterval = null;
        }
    }

    /**
     * Return queue metrics (pending, syncing, synced, failed)
     */
    getQueueStats() {
        return this.db.prepare(`
            SELECT status, COUNT(*) as count FROM payload_queue GROUP BY status
        `).all();
    }

    /**
     * Purge synced logs older than retainDays to keep database lightweight
     */
    purgeSynced(retainDays = 7) {
        const cutoffDate = new Date(Date.now() - retainDays * 24 * 60 * 60 * 1000).toISOString();
        const stmt = this.db.prepare(`DELETE FROM payload_queue WHERE status = 'SYNCED' AND created_at < ?`);
        const result = stmt.run(cutoffDate);
        return result.changes;
    }
}

module.exports = TrustOfflineBuffer;
