import time
import numpy as np
import onnxruntime as ort


def create_optimized_piper_session(
    model_path: str,
    device: str = "cuda",
    cpu_threads: int = 4
) -> ort.InferenceSession:
    """
    Creates an ONNX Runtime InferenceSession tailored for low-latency 
    Piper TTS inference across CUDA, TensorRT, DirectML, or CPU.
    """
    options = ort.SessionOptions()

    # 1. Enable full graph optimizations (constant folding, node fusion)
    options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL

    # 2. Sequential execution reduces overhead for single-stream audio generation
    options.execution_mode = ort.ExecutionMode.ORT_SEQUENTIAL

    # 3. Thread pool allocation for CPU operator parallelization
    options.intra_op_num_threads = cpu_threads  # Parallelize operators across cores
    options.inter_op_num_threads = 1            # Run graph nodes sequentially

    # 4. Configure hardware execution provider priority chain
    providers = []

    if device.lower() == "cuda":
        cuda_opts = {
            "device_id": 0,
            "arena_extend_strategy": "kNextPowerOfTwo",
            "gpu_mem_limit": 2 * 1024 * 1024 * 1024,  # 2 GB limit
            "cudnn_conv_algo_search": "EXHAUSTIVE",    # Benchmark algorithms on load
            "do_copy_in_default_stream": True,
        }
        providers.append(("CUDAExecutionProvider", cuda_opts))

    elif device.lower() == "tensorrt":
        trt_opts = {
            "device_id": 0,
            "trt_max_workspace_size": 2147483648,      # 2 GB workspace
            "trt_fp16_enable": True,                    # Half-precision math
            "trt_engine_cache_enable": True,            # Cache compiled engine file
            "trt_engine_cache_path": "./trt_cache",
        }
        providers.append(("TensorrtExecutionProvider", trt_opts))
        # Fallback to CUDA if TensorRT build fails
        providers.append(("CUDAExecutionProvider", {}))

    elif device.lower() == "directml":
        # DirectML provider for cross-platform GPU (Windows/Linux AMD/Intel/NVIDIA)
        dml_opts = {"device_id": 0}
        providers.append(("DmlExecutionProvider", dml_opts))

    elif device.lower() == "openvino":
        # Intel OpenVINO CPU acceleration
        openvino_opts = {
            "device_type": "CPU_FP32",
            "num_of_threads": cpu_threads,
        }
        providers.append(("OpenVINOExecutionProvider", openvino_opts))

    # CPU provider is always appended as the ultimate fallback
    providers.append(("CPUExecutionProvider", {}))

    # Instantiate the optimized session
    session = ort.InferenceSession(model_path, options, providers=providers)
    
    print(f"Loaded Piper session with active provider: {session.get_providers()[0]}")
    return session


def synthesize_phonemes(
    session: ort.InferenceSession,
    phoneme_ids: list[int],
    noise_scale: float = 0.667,
    length_scale: float = 1.0,
    noise_w: float = 0.8,
    speaker_id: int | None = None
) -> tuple[np.ndarray, float]:
    """
    Executes Piper ONNX model inference and measures synthesis latency.
    """
    # Format inputs required by Piper ONNX graphs
    x = np.array([phoneme_ids], dtype=np.int64)
    x_lengths = np.array([len(phoneme_ids)], dtype=np.int64)
    scales = np.array([noise_scale, length_scale, noise_w], dtype=np.float32)

    inputs = {
        "input": x,
        "input_lengths": x_lengths,
        "scales": scales,
    }

    # Include speaker ID tensor if using a multi-speaker model
    input_names = [i.name for i in session.get_inputs()]
    if "sid" in input_names and speaker_id is not None:
        inputs["sid"] = np.array([speaker_id], dtype=np.int64)

    # Benchmark inference latency
    start_time = time.perf_counter()
    outputs = session.run(None, inputs)
    latency_ms = (time.perf_counter() - start_time) * 1000

    # Output audio tensor (1, 1, N) or (1, N) -> flatten to 1D float32 array
    audio_pcm = outputs[0].squeeze()
    
    return audio_pcm, latency_ms


if __name__ == "__main__":
    MODEL_PATH = "my_custom_voice.onnx"

    # Example phoneme sequence IDs (e.g., generated by piper-phonemize or espeak-ng)
    sample_phoneme_ids = [1, 10, 42, 15, 8, 23, 19, 31, 2]

    # Initialize GPU or CPU Session
    try:
        session = create_optimized_piper_session(MODEL_PATH, device="cuda", cpu_threads=4)
        audio, ms = synthesize_phonemes(session, sample_phoneme_ids)
        print(f"Inference complete: {len(audio)} samples generated in {ms:.2f} ms")
    except Exception as e:
        print(f"Inference failed: {e}")
